### ISSUE TITLE
Add the statistical context to a questionnaire

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#10]
A series pools a set of statistical operations sharing a homogeneous mthodology and a main business characteristic.
It's characterised by:
- a short name (or ID ?)
- a label

A statistical operation can be defined as a set of collection, capture, process and data dissemination unique and consistent. Each statistical operation can contain one or several data collection.
It's characterised by:
- a series
- a year

A data collection (or a data collection campaign) is a survey data collection realization period. Each data collection can contain one ore several questionnaire.
It's characterised by:
- a statistical operation
- a period (M01 - January,...,T02 - Second quarter,etc.)

Starting hypothesis: all these concepts are created outside Pogues.

We need to add these concepts in the model.

**Comment by FranckCo** [comment]
The solution agreed upon is to rename the current Survey element into DataCollection and to add an 'uri' attribute to it. Also change cardinality: a questionnaire can be attached to several data collections. See commit 9f50429279ed96c516dff87afae6b765ae068b30.

**Comment by ThomasPO** [comment]
Done. Issue closed.
