### ISSUE TITLE
Link between Variables and CollectedVariable

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#12]
There is no link between the variable in the <Variables> wrap and the <CollectedVariable> variable created in the response element.

For exemple: if we delete a collected variable in a response, we can't delete it in the <Variables> wrap, because we don't know what is the variable to delete.

One idea is to have a CollectedVariableReference in the ResponseType (instead of the CollectedVariable) as we did for the code list.

**Comment by FranckCo** [comment]
Fixed in commit 61598f660bb63a3607605e5d323cda21b81ea42b.

**Comment by ThomasPO** [comment]
Ok, issue closed.
