### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by a-cordier** [InseeFr/Pogues-Model#13]
Project does not compile any more since fields has been renamed in the schema.

See commits:

453f034a151092396f621ded6d1ded47ff2fa49b
7390a491456a9ff124c02dd2078a35a36b9ffa51
c88a4f2323bafd24c4425f158c6c463a037fdfb2
dd428882c8858ef06a91a58e996600d69c062f9a
9f50429279ed96c516dff87afae6b765ae068b30

More over, it looks like there's a mapping issue as just replacing Survey by DataCollection as a type in QuestionnaireFactory does not solve this issue: No setter is added to Questionnaire for DataCollection when sources are generated from schema.

**Comment by bwerquin** [comment]
Fixed.
