### ISSUE TITLE
Consistency in naming: can we stop mixin upper/lower case ?

### ISSUE THREAD

**Issue by a-cordier** [InseeFr/Pogues-Model#15]
Pogues naming convention tells that elements are uppercase while attributes are lowercase.

This makes us end with a JSON where keys are inconsistently distributed between lower/uppercase, making the model hard to predict.

One solution would be to use lower camel case everywhere in the model.

**Comment by FranckCo** [comment]
These naming rules are global for Insee and don't address or favor any specific language.
