### ISSUE TITLE
Measurement unit

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#19]
Subject to discuss.

We need to define a measurement unit attached to a NumericDatatypeType.
One is to mangage an enumeration.

It would be a first version to manage a measurement unit because few special cases must be studied (manage a measurement unit depending on a variable, etc.).

Example of enumeration:
€
K€ (or thousands of euros or both?)
%
m²
tonnes
m³
litres
10³Nm³
MWh
kW
hours (maybe we should create a DurationDatatypeType?)
hours / week
days worked / week (jours travaillés/ semaine)
hours / year
days / year
working days
calendar days

Finally, maybe it's better to have a xs:token?

**Comment by FranckCo** [comment]
Propose to close (see commit e8a12ad1e33816cdd246fe6f6e29661a14c6b0c0)

**Comment by ThomasPO** [comment]
Ok. Issue closed
