### ISSUE TITLE
Updating the schema for the CodeListSpecification

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Pogues-Model#2]
Two things in fact must be done :

1. the [uri element](https://github.com/InseeFr/Pogues-Model/blob/master/src/main/resources/xsd/Questionnaire.xsd#L164) should be renamed retrievalURI or something like this because it holds the request that returns the values of a classification level,
2. we should also add a label element for naming purpose.

**Comment by FranckCo** [comment]
Fixes with commits 956baa3 and 95e592d.
