### ISSUE TITLE
"Please, specify" option

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#23]
Use case: add the "Please, specify" option.

"Please, specify" is a request for additional information from a list of choices defined a priori (single or multiple choice question).
This additional information is related to a response domain and triggered  when a specific response value is selected or typed.

It's characterised by:

a **label** (can be something else than "Please, specify") 
a **response** to collect the specified value 
a **link** to a response domain 
a **trigger value** to display the "Please, specify" request

Side note:
a single choice question contain only one response (a code list) 
a multiple choice question contain one response (code list or boolean) by choice

**Comment by ThomasPO** [comment]
It seems to be a clarification question, but it's not really a question too. We can't use the question outside the context. What do we decide?

**Comment by FranckCo** [comment]
We create an optional ClarificationQuestion child of QuestionType. The triggering of the clarification question can be made through the FlowControl element (which will replace the GoTo).

**Comment by ThomasPO** [comment]
Validated. Issue closed.

**Comment by BulotF** [comment]
1) Making the difference between an ex-Goto FlowControl and a Clarification FlowControl is complicated.
2) Triggering the clarified response is complicated too : it needs to parse the FlowControl's Expression.
3) ex-Goto FlowControl is used to link a Child to another in a n-n relationship. We need to link a response to a clarificationQuestion in a n-1 relationship.


My proposal :
- stop using FlowControl for ClarificationQuestion
- add a "responseToClarify id" in ClarificationQuestion would be enough to make the link. In MCQ or tables, this link would tell where the ClarificationQuestion should be shown
- DDI needs to catch the value and the related code of the Clarified CodeResponse : I don't know if Expression is the good way to keep the information in Pogues model (it is the good way in all other cases : when the ClarificationQuestion is not link to a SingleChoiceQuestion or a MCQ)

**Comment by bwerquin** [comment]
We create an optional Enum to make the difference between an ex-Goto FlowControl and a Clarification FlowControl

**Comment by FranckCo** [comment]
Done in commit dfab3d2ddb7bf6a5155da5fdc03cff3872e0c9bc
