### ISSUE TITLE
Redesign the type of question "Table"

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#26]
We have to identify each data cell. Could we use a cell coordinates system instead of the mappingType element?

Use cases: 

- bind a collected variable to a response...and well managed the table structure changes (for exemple if a table with 4 lines and 3 columns become a table with 3 lines and 4 columns).
- define a specific cell as "no data by definition" (a no meaning intersection)

**Comment by ThomasPO** [comment]
Issue dropped

**Comment by ThomasPO** [comment]
Issue dropped

**Comment by FranckCo** [comment]
Also added an identifier to responses in order to be able to reference them in mappings (commit 8e78f241dc94514ca233a90ca306338c68e94584).

**Comment by ThomasPO** [comment]
Validated. Issue closed.
