### ISSUE TITLE
Change the Minimum and Maximum type for a NumericDatatypeType

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#32]
About the NumericDatatypeType type.
We have to define a Minimum and a Maximumas as Decimal.
Possible to change it in decimal instead of integer?

**Comment by bwerquin** [comment]
Done

**Comment by ThomasPO** [comment]
Done. 
Issue closed

**Comment by ThomasPO** [comment]
Done.
Issue closed
