### ISSUE TITLE
Date and duration format

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Pogues-Model#34]
PoguesModel is currently managing only one date format : ddmmyyyy.

In order to manage other date and duration questions, we need to change Pogues model in order to allow :
-2 new date format : mmyyyy and yyyy
-duration format composed of years, months, days, hours, minutes (for exemple survey can ask for a duration in years-months or months-days or hours-minutes and so one)
 
We can also notice that there will be 4 new "numeric" duration : hours, days, months, years. But, as they will be managed with 4 corresponding new measurement units for numeric format, no consequence for PoguesModel.
 
The new PoguesModel should be ideally compatible with old/current questionnaires in which a DateDatatype only means the date format ddmmyyyy. If not, we should remember to correct json file of these questionnaires before we reuse them.
 
Thanks a lot !

**Comment by bwerquin** [comment]
Done:
c3819b0c5fb27b88309e8dc834c76bc4e8854578
287c1d8b98db7b3b0b3e8d98c86d2b18af96d59f
