### ISSUE TITLE
Add QuestionType (or ResponseFormat) ?

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#4]
We want to differentiate several Response format or question type. It's a characteristic of the question.
The question type can be : SIMPLE, SINGLE, MULTIPLE and TABLE

This classification is maybe not the final release but it could help to better manage the serialization.

Can we add this information in the Model ?

**Comment by FranckCo** [comment]
How does it combine with current QuestionType attributes `simple` and `open`?

**Comment by ThomasPO** [comment]
At this time, we don't use the current attributes `simple` and `open`
In fact, we don't really know the best way to design a question type (or responses format). We tested other questionnaire design interface and no structuring was clearly standard.

If we defined the current attribute `simple` as the opposite of  `multiple responses`  
and the current attribute `open` as the opposite of `closed`

I'll say that:
- SIMPLE means `simple` and `open` (for the text/numeric data type) or `closed` (for the boolean data type)
- SINGLE means  `simple` and `closed`
- MULTIPLE means  `multiple` and `closed`
- Table means `multiple` and `open` or `closed` (depends on the data type)

We can't define a mapping between the two current attributes and this proposal of structuring.

Even if it seemed logical to define closed question and simple question, do we keep these attributes?

**Comment by FranckCo** [comment]
Schema modifications done. Can I have one line of description for each enumeration value?

**Comment by BoogalooJB** [comment]
In Pogues, when we serialize a questionnaire, we add a type property to some objects (for example 'QuestionType', 'SequenceType', 'NumericDatatypeType'....). I thought it was used by the json to xml converter to indicate which extension of an abstract type we were using, but I might be wrong.
Anyway, for now, there might be a naming conflict between this generic type property, and the specific question type property this issue suggest to add. Just asking, really not sure.

**Comment by ThomasPO** [comment]
- a SIMPLE question is a question made of a label and only one response domain whichever its type be: text, numeric, date, boolean, or less frequently any type available in the DDI schemas.

- a SINGLE_CHOICE question is a question made of a label and a response domain typed as a code list (which is an information axis). This type of question allows to the respondent to select one response from a predefined list.

- a MULTIPLE_CHOICE question is a form of assessment in which respondents are asked to select the best possible answer out of a number of choices forming an information axis. Each modality is akin to a sub-question.

- a TABLE question is a means of linking various information carried by the rows and the columns. The information located at the intersection of a row and a column corresponds to a response. We can precisely name it a two-way table

**Comment by ThomasPO** [comment]
New proposal for MULTIPLE_CHOICE and TABLE questions:

- a MULTIPLE_CHOICE question is a question made of a label and a response domain typed as a code list (which is an information axis). In this case, each modality is akin to a sub-question. This type of question allows to the respondent to select the best possible answers out of a number of choices from a predefined list.

-  a TABLE is double entry table. It's a question is a question made of a label and a response domain represented as two dimensions. The information located at the intersection of a row and a column corresponds to a response.

**Comment by ThomasPO** [comment]
New proposal:

- a SIMPLE question is a question made of a label and only one response domain whichever its type be: text, numeric, date, boolean, or less frequently any type available in the DDI schemas.

a SINGLE_CHOICE question is a question made of a label and a response domain typed as a code list. This type of question allows to the respondent to select one single response from a predefined list.

- A MULTIPLE_CHOICE question is a  question whose label is the mutual part of several sub-questions (constituting a coherent whole i.e an information axis). Each modality of the information axis is peculiar to a specific response domain. This type of question allows to the respondent to select the best possible answers out of a number of choices from a predefined list.

- A TABLE is a two-way table. It's a question made of a label and a response domain defined by two dimensions. The information located at the intersection of a row and a column corresponds to a response.

**Comment by ThomasPO** [comment]
It's a general subjetc. New issue created [here](https://github.com/InseeFr/Pogues-Model/issues/11)

**Comment by ThomasPO** [comment]
Closed.
