### ISSUE TITLE
Add a specific modality attached to the Response

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#5]
We want to specify a specific modality (the most significant case is the modality `Don't know` or later `Refusal`) attached to  the `Response`
For the moment, a specific modality can be attached to a response only for a question type `Single` 

A `SpecificModality` is defined by:

- a Label (the label of the modality)
- a Value (the Value of the code)
- a DynamicBehaviour: an enumeration with the values `FIRST_INTENTION` and `SECOND_INTENTION` (the dynamic behaviour in the generated questionnaire)
- a UrgingMessage (the message for the respondant)

**Comment by FranckCo** [comment]
Closed with commit d21f387ae1e7f9e7f020adfecc764e4cb102ec32
