### ISSUE TITLE
GoTo or IfThenElse logic to specif the dynamic of a questionnaire

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Pogues-Model#54]
Survey designer should have the possibility to choose if they prefer to describe the dynamic of their questionnaire (jump directly to a question, a sequence or a subsequence according to a condition on some variables) with a GoTo or an IfThenElse logic. Therefore, PoguesModel should enable this choice thanks to a dedicated parameter. However, DDI can not handle this information. 
Thanks for your help !

**Comment by ORogel** [comment]
PR #59
