### ISSUE TITLE
Iteration : Maximum could be a formula

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Pogues-Model#56]
Maximum could be a formula. Example : for VQS Survey, the iteration maximum will be a collected variable corresponding to the number of people living in the household.

Thank you to redesign:
 <xs:complexType name="DynamicIterationType">
    <xs:complexContent>
      <xs:extension base="IterationType">
        <xs:sequence>
            <xs:element name="Minimum" type="xs:nonNegativeInteger" minOccurs="0"/>
            <xs:element name="Maximum" type="xs:nonNegativeInteger" minOccurs="0"/>
...
into: 
 <xs:complexType name="DynamicIterationType">
    <xs:complexContent>
      <xs:extension base="IterationType">
        <xs:sequence>
            <xs:element name="Minimum" type="xs:nonNegativeInteger" minOccurs="0"/>
            <xs:element name="Maximum" type="ExpressionType" minOccurs="0"/>

**Comment by ORogel** [comment]
https://github.com/InseeFr/Pogues-Model/commit/f8f4db7772c825a87404abd1a643adb3c28f75a4
