### ISSUE TITLE
Add the concept "variable" in the model

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#7]
We have to add the concept of variable in the model.

A variable can a be collected, calculated or external.
A collected variable is a statistical variable collected within a questionnaire for the survey need.
An external variable is a variable 
A calculated variable is a variable calculated from others variables including the calculated variables.

An external variable refers to a variable not collected in the questionnaire, but useful for personalization.
For example, it may be a collection wave number for filtering questions, a date to be displayed in the wording of a question, etc.

We also need to reference these three kind of variable to write the conditions (or more generally the controls) in all the questionnaire. That's why it should be interesting to wrap the variables in an element "Variables" as we did whith "CodeLists".

To explain more, an modelization example below....but would it be better to use an "abstract"?, typed the variables? others ???

``` xml


  <xs:element name="Variables">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CollectedVariable" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="ExternalVariable" minOccurs="0" maxOccurs="unbounded"/>        
        <xs:element ref="CalculatedVariable" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="CollectedVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:token"/>
        <xs:element name="Label" type="xs:token"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="CalculatedVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:token"/>
        <xs:element name="Label" type="xs:token"/>
        <xs:element name="Formula" type="xs:token"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>


  <xs:element name="ExternalVariable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:token"/>
        <xs:element name="Label" type="xs:token"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>


```

Consequence, we add the element <CollectedVariables> to the ResponseType:

``` xml
  <xs:complexType name="ResponseType">
    <xs:sequence>
      <xs:element name="CodeListReference" type="xs:token" minOccurs="0"/>
      <xs:element name="Datatype" type="DatatypeType"/>
      <xs:element name="Value" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="NonResponseModality" type="NonResponseModalityType" minOccurs="0"/>
      <xs:element ref="CollectedVariable"/>
    </xs:sequence>
    <xs:attribute name="simple" type="xs:boolean"/>
    <xs:attribute name="mandatory" type="xs:boolean"/>
  </xs:complexType>

```

**Comment by ThomasPO** [comment]
One thing: maybe it's not useful to have a label for the external variable because we can't store it in DDI.

**Comment by FranckCo** [comment]
The preferred modelization is to have a VariableType base type and extension types for collected, calculated and external variables. See commit 453f034a151092396f621ded6d1ded47ff2fa49b.

**Comment by ThomasPO** [comment]
Done.
