### ISSUE TITLE
Manage hierarchical code lists

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#8]
We have to manage a hierarchical code lists. Its means that a code may contain a code that may contain a code, etc. (as a recursive description). 

One idea: create a type: "CodeType" containing a code typed "CodeType" and refers it in the CodeList:

``` xml

  <xs:element name="CodeType">
   <xs:complexType>
     <xs:sequence>
       <xs:element name="Value" type="xs:token"/>
        <xs:element name="Label" type="xs:string"/>
        <xs:element name="Code" type="CodeType"/>
       </xs:sequence>
     </xs:complexType>
    </xs:element>      

```

The CodeList description could become:

``` xml

  <xs:element name="CodeList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Name" type="xs:token"/>
        <xs:element name="Label" type="xs:token"/>
        <xs:element name="Code" type="CodeType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

```

Maybe should we add a Code directly in the CodeList without creating the CodeType?

**Comment by FranckCo** [comment]
There are two approaches to this:

- The model proposed above, which is close to the DDI model, where the code hierarchy is represented in the XML structure (although there is also a reference to the level in DDI)
-  The SDMX or SKOS way, where all the items are directly attached to the code list and the structure is represented by explicit constructs (<Parent/> element in SDMX, broader/narrower properties in SKOS).

For now it seems that the second approach is easier to use for Pogues, so this is what we implement (see commit dd428882c8858ef06a91a58e996600d69c062f9a).

**Comment by ThomasPO** [comment]
Ok. Issue closed.
