### ISSUE TITLE
Dynamic Unit on InputNumber

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Pogues-Model#85]
see Lunatic: : https://github.com/InseeFr/Lunatic/issues/668

**Comment by QRuhier** [comment]
see https://github.com/InseeFr/Pogues/issues/695#issuecomment-2233423439
For a collected variable, in Datatype object, if type is "NumericDatatypeType" we need to add an optional key : 
"dynamicUnit" : boolean | undefined

**Comment by BulotF** [comment]
Pour gérer l'identification du caractère dynamique de l'unité : ajout de :
<xs:element name="IsDynamicUnit" type="xs:boolean" minOccurs="0"/>

Pour gérer le fait que Unit pour désormais soit contenir une Uri vers RMéS, soit un nom de variable entre $ :
<xs:element name="Unit" type="xs:token" minOccurs="0">
(avec mise à jour du commentaire)

**Comment by JulienCarmona** [comment]
1pt
