### ISSUE TITLE
Add a status to the questionnaire

### ISSUE THREAD

**Issue by ThomasPO** [InseeFr/Pogues-Model#9]
We have to know if a questionnaire is "in progress" or "published"....maybe other status we will define all the process.

Idea: add an attribut "status" to the questionnaire.

**Comment by bwerquin** [comment]
How to ensure the coherence of the two versions of the questionnaire (metadate repo and in Pogues) ?

**Comment by ThomasPO** [comment]
I know we have to define the questionnaire lifecycle...but firstly i imagine:

- if the status is published,so the questionnaire **won't be updatable** from Pogues. You only can see the questionnaire in Pogues and visualize the generated questionnaire.

**Comment by FranckCo** [comment]
Since we don't have a precise idea of the questionnaire lifecycle stages, I suggest that for now we stick to a simple boolean attribute indicating if the questionnaire is final or not (commit fffe26defc96bf51b18f15641b73d9cfb1102d62).

**Comment by ThomasPO** [comment]
Done. Issue closed.
