### ISSUE TITLE
Suggester: missing properties

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Pogues-Model#90]
- [x] the `stemmer` property is missing in the query parser params (NB: it is present in fields)
- [x] `rules` property: can be either `"soft"` or an array of strings (currently it is modeled as a string).
- [x] `synonyms` property: keys = string, values = array of strings

Note: "rules" being either a string or an array is flawed, yet we'll do it like this for now so to not have to change Lunatic in short term.

**Comment by laurentC35** [comment]
Done
